/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package modul_7;
import javax.swing.DefaultListModel;

/**
 *
 * @author PC RPL - R1
 */
public class tModul7 extends javax.swing.JFrame {

    /**
     * Creates new form tModul7
     */
    public tModul7() {
        initComponents();
         DefaultListModel<String> listModel = new DefaultListModel<>();
        lsMinuman.setModel(listModel);
        taAreaKota.setText("");  // Mengosongkan AreaKota
        cbMakanan.removeAllItems();  // Mengosongkan JComboBox
        lsMinuman.setModel(new DefaultListModel<>());  // Mengosongkan JList
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taAreaKota = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsMinuman = new javax.swing.JList<>();
        cbMakanan = new javax.swing.JComboBox<>();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bSisip = new javax.swing.JButton();
        tfMakanan = new javax.swing.JTextField();
        lKota = new javax.swing.JLabel();
        lMakanan = new javax.swing.JLabel();
        lMinuman = new javax.swing.JLabel();
        tfMinuman = new javax.swing.JTextField();
        tfKota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taAreaKota.setColumns(20);
        taAreaKota.setRows(5);
        jScrollPane1.setViewportView(taAreaKota);

        jScrollPane2.setViewportView(lsMinuman);

        cbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mie Yamin" }));
        cbMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakananActionPerformed(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bSisip.setText("Sisip");
        bSisip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSisipActionPerformed(evt);
            }
        });

        lKota.setText("Kota");

        lMakanan.setText("Makanan");

        lMinuman.setText("Minuman");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lKota)
                            .addComponent(bTambah))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lMakanan)
                                    .addComponent(cbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lMinuman))
                                .addGap(213, 213, 213))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSisip)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bUbah)
                                    .addComponent(bHapus))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfKota, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(tfMakanan))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKota)
                    .addComponent(lMakanan)
                    .addComponent(lMinuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(bTambah)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus)
                        .addGap(18, 18, 18)
                        .addComponent(bUbah)
                        .addGap(18, 18, 18)
                        .addComponent(bSisip)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMakananActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
// Mengisi JTextArea dengan daftar kota
    taAreaKota.append("Gresik" + "\n");
    taAreaKota.append("Malang" + "\n");
    taAreaKota.append("Surabaya" + "\n");
    taAreaKota.append("Bogor" + "\n");
    
    // Mengisi JComboBox dengan daftar makanan
    cbMakanan.insertItemAt("Rujak", 0);
    cbMakanan.insertItemAt("Rawon", 1);
    cbMakanan.insertItemAt("Sate", 2);
    cbMakanan.insertItemAt("Seblak", 2);
    
    // Membuat instance dari DefaultListModel untuk JList
    DefaultListModel<String> listModel = new DefaultListModel<>();
    
    // Menambahkan item ke dalam listModel
    listModel.addElement("Sprite");
    listModel.addElement("Fanta");
    listModel.addElement("Es Batu");
    listModel.addElement("Kopi");
    
    // Mengatur model JList dengan listModel
    lsMinuman.setModel(listModel);
    }//GEN-LAST:event_bTambahActionPerformed

    private void bSisipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSisipActionPerformed

    
    // Menyisipkan daftar kota dari TextField ke JTextArea
    String inputKota = tfKota.getText();
    if (!inputKota.isEmpty()) {
        taAreaKota.append(inputKota + "\n");
    }
    
    // Menyisipkan daftar makanan dari TextField ke JComboBox
    String inputMakanan = tfMakanan.getText();
    if (!inputMakanan.isEmpty()) {
        cbMakanan.addItem(inputMakanan);
    }
    
    // Menyisipkan daftar minuman dari TextField ke JList
    DefaultListModel<String> listModel = (DefaultListModel<String>) lsMinuman.getModel();
    String inputMinuman = tfMinuman.getText();
    if (!inputMinuman.isEmpty()) {
        listModel.addElement(inputMinuman);
    }
    }//GEN-LAST:event_bSisipActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
// Menghapus kota pertama dari JTextArea (AreaKota)
    try {
        String[] lines = taAreaKota.getText().split("\n");
        taAreaKota.setText("");  // Kosongkan JTextArea
        for (int i = 1; i < lines.length; i++) {  // Mulai dari index 1 untuk menghapus baris pertama
            taAreaKota.append(lines[i] + "\n");
        }
    } catch (Exception e) {
        // Tangani jika JTextArea kosong
    }

    // Menghapus makanan pertama dari JComboBox (CbMakanan)
    if (cbMakanan.getItemCount() > 0) {
        cbMakanan.removeItemAt(0);
    }

    // Menghapus minuman pertama dari JList (ListMinuman)
    DefaultListModel<String> listModel = (DefaultListModel<String>) lsMinuman.getModel();
    if (!listModel.isEmpty()) {
        listModel.remove(0);
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // Menghapus kota pertama dari JTextArea (AreaKota)
    try {
        String[] lines = taAreaKota.getText().split("\n");
        taAreaKota.setText("");  // Kosongkan JTextArea
        for (int i = 1; i < lines.length; i++) {  // Mulai dari index 1 untuk menghapus baris pertama
            taAreaKota.append(lines[i] + "\n");
        }
    } catch (Exception e) {
        // Tangani jika JTextArea kosong
    }

    // Menghapus makanan pertama dari JComboBox (CbMakanan)
    if (cbMakanan.getItemCount() > 0) {
        cbMakanan.removeItemAt(0);
    }

    // Menghapus minuman pertama dari JList (ListMinuman)
    DefaultListModel<String> listModel = (DefaultListModel<String>) lsMinuman.getModel();
    if (!listModel.isEmpty()) {
        listModel.remove(0);
    }
         
    }//GEN-LAST:event_bUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tModul7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tModul7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tModul7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tModul7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tModul7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSisip;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbMakanan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lKota;
    private javax.swing.JLabel lMakanan;
    private javax.swing.JLabel lMinuman;
    private javax.swing.JList<String> lsMinuman;
    private javax.swing.JTextArea taAreaKota;
    private javax.swing.JTextField tfKota;
    private javax.swing.JTextField tfMakanan;
    private javax.swing.JTextField tfMinuman;
    // End of variables declaration//GEN-END:variables

}
